## Numpy 

In [1]:
import numpy as np

In [2]:
a=np.arange(10)
b=np.arange(20)

In [3]:
print(a)
b

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
a= np.arange(90).reshape(5,6,3)

In [5]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]],

       [[54, 55, 56],
        [57, 58, 59],
        [60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71]],

       [[72, 73, 74],
        [75, 76, 77],
        [78, 79, 80],
        [81, 82, 83],
        [84, 85, 86],
        [87, 88, 89]]])

In [6]:
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(type(a))

90
(5, 6, 3)
3
int32
4
<class 'numpy.ndarray'>


In [7]:
b=np.array([1.0,3.0,5.0])
print(b)
print(type(b))
print(b.size)
print(b.dtype)

[1. 3. 5.]
<class 'numpy.ndarray'>
3
float64


In [8]:
c=np.eye(5)
dtype=np.int64
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
d=np.linspace(20,100,5,endpoint=True)
d

array([ 20.,  40.,  60.,  80., 100.])

In [10]:
e=np.logspace(20,100,5,endpoint=True,base=2)
e

array([1.04857600e+06, 1.09951163e+12, 1.15292150e+18, 1.20892582e+24,
       1.26765060e+30])

In [11]:
help(np.fromfunction)

Help on function fromfunction in module numpy:

fromfunction(function, shape, **kwargs)
    Construct an array by executing a function over each coordinate.
    
    The resulting array therefore has a value ``fn(x, y, z)`` at
    coordinate ``(x, y, z)``.
    
    Parameters
    ----------
    function : callable
        The function is called with N parameters, where N is the rank of
        `shape`.  Each parameter represents the coordinates of the array
        varying along a specific axis.  For example, if `shape`
        were ``(2, 2)``, then the parameters would be
        ``array([[0, 0], [1, 1]])`` and ``array([[0, 1], [0, 1]])``
    shape : (N,) tuple of ints
        Shape of the output array, which also determines the shape of
        the coordinate arrays passed to `function`.
    dtype : data-type, optional
        Data-type of the coordinate arrays passed to `function`.
        By default, `dtype` is float.
    
    Returns
    -------
    fromfunction : any
        The 

In [12]:
ex=np.fromfunction(lambda i,j:i*j,(3,3),dtype=int)
ex

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

# Array Operations

In [13]:
m=np.arange(10).reshape(2,5)
m

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
n= m.transpose()
n

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [15]:
#Matrix multiplication
m@n

array([[ 30,  80],
       [ 80, 255]])

In [16]:
print(m+m)
print(m*m)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]
[[ 0  1  4  9 16]
 [25 36 49 64 81]]


In [17]:
print(m)
m.sum(axis=0)

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([ 5,  7,  9, 11, 13])

In [18]:
m.sum()

45

In [19]:
m.min(),m.max()

(0, 9)

## Universal functions

In [20]:
b=m*np.pi/10
b

array([[0.        , 0.31415927, 0.62831853, 0.9424778 , 1.25663706],
       [1.57079633, 1.88495559, 2.19911486, 2.51327412, 2.82743339]])

In [21]:
c=np.cos(b)
c

array([[ 1.00000000e+00,  9.51056516e-01,  8.09016994e-01,
         5.87785252e-01,  3.09016994e-01],
       [ 6.12323400e-17, -3.09016994e-01, -5.87785252e-01,
        -8.09016994e-01, -9.51056516e-01]])

## Array Slicing : Accessing Subarrays

In [22]:
a=np.arange(51)
muloften=a[0:51:10]
muloften

array([ 0, 10, 20, 30, 40, 50])

In [23]:
muloften[3]

30

In [24]:
print(muloften[2:4])

[20 30]


In [25]:
muloften[2:-2]

array([20, 30])

In [26]:
muloften[:]

array([ 0, 10, 20, 30, 40, 50])

In [27]:
mat=np.arange(20).reshape(4,5)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
mat[2,3]

13

In [29]:
mat[0:3,0:4]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [30]:
mat[3,:]

array([15, 16, 17, 18, 19])

In [31]:
mat[:,2]

array([ 2,  7, 12, 17])

In [32]:
mat.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
for i in mat:
    print(i)
a=np.arange(20).reshape(5,4)    
a

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [35]:
help(a.flat)

Help on flatiter object:

class flatiter(builtins.object)
 |  Flat iterator object to iterate over arrays.
 |  
 |  A `flatiter` iterator is returned by ``x.flat`` for any array `x`.
 |  It allows iterating over the array as if it were a 1-D array,
 |  either in a for-loop or by calling its `next` method.
 |  
 |  Iteration is done in row-major, C-style order (the last
 |  index varying the fastest). The iterator can also be indexed using
 |  basic slicing or advanced indexing.
 |  
 |  See Also
 |  --------
 |  ndarray.flat : Return a flat iterator over an array.
 |  ndarray.flatten : Returns a flattened copy of an array.
 |  
 |  Notes
 |  -----
 |  A `flatiter` iterator can not be constructed directly from Python code
 |  by calling the `flatiter` constructor.
 |  
 |  Examples
 |  --------
 |  >>> x = np.arange(6).reshape(2, 3)
 |  >>> fl = x.flat
 |  >>> type(fl)
 |  <class 'numpy.flatiter'>
 |  >>> for item in fl:
 |  ...     print(item)
 |  ...
 |  0
 |  1
 |  2
 |  3
 |  4
 |  

In [36]:
#deepcopy 
new=np.arange(7)
cnew=new.copy()
cnew

array([0, 1, 2, 3, 4, 5, 6])

In [37]:
#shallowcopy
dnew=new[:]
dnew

array([0, 1, 2, 3, 4, 5, 6])

In [38]:
#assignment
enew = new
enew

array([0, 1, 2, 3, 4, 5, 6])

In [39]:
print("Location of the above variables")
print("new=",id(new))
print("cnew=",id(cnew))
print("dnew=",id(dnew))
print("enew=",id(enew))


Location of the above variables
new= 2086792069648
cnew= 2086791761232
dnew= 2086792071008
enew= 2086792069648


In [40]:
dnew[-1]=0 #changing the element of shallow copy variable to see what impact it has on the rest of the variables 
dnew

array([0, 1, 2, 3, 4, 5, 0])

In [41]:
new #original

array([0, 1, 2, 3, 4, 5, 0])

In [42]:
enew #assignment variable

array([0, 1, 2, 3, 4, 5, 0])

In [43]:
cnew #deepcopy variable

array([0, 1, 2, 3, 4, 5, 6])

In [44]:
#different methods of checking
print(cnew is new)
print(cnew.flags.owndata)
print(new.flags.owndata)
print(dnew.flags.owndata)
print(enew.flags.owndata)

False
True
True
False
True


## Boolean Indexing 

In [45]:
z=np.arange(16).reshape(4,4)

z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
z[z>14]=0
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0]])

In [47]:
z[np.logical_and(z>2,z<=10)]=7
z

array([[ 0,  1,  2,  7],
       [ 7,  7,  7,  7],
       [ 7,  7,  7, 11],
       [12, 13, 14,  0]])

In [48]:
z>3

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [49]:
z[:]=0
z

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## Avoiding Loops

In [50]:
A = 10
B = 20
xmin = ymin = 0.0
xmax = ymax = 10.0

x = np.linspace(xmin, xmax, B, endpoint=False)
y = np.linspace(ymin, ymax, A, endpoint=False)

print(x.shape)
print(y.shape)
y

(20,)
(10,)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
#time taken for calculation 
import time
t_in=time.time()
abc=np.zeros((A,B))
for i in range(A):
    for j in range(B):
        abc[i,j]= np.cos(2*np.pi*x[j]*y[i])

t_fi=time.time()
print("Time taken=" , t_fi-t_in)

Time taken= 0.0009996891021728516


In [52]:
help(np.meshgrid())

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

In [53]:
x2d,y2d= np.meshgrid(y,x,indexing='ij')
print(x2d[:,0])
print(x2d[0,:])
print(y2d[:,0])
print(y2d[0,:])

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [54]:
#concatenation

a= np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.concatenate([b,a])
c

array([5, 6, 7, 8, 1, 2, 3, 4])

In [55]:
grid = np.array([[1,2,3,4],
                [5,6,7,8]])
print(np.concatenate([grid,grid,grid],axis=1))
print(np.concatenate([grid,grid],axis=0))


[[1 2 3 4 1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8 5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [56]:
#splitting 
abc=[1,2,3,4,5,6,7,8,9,10,11,12]
a,b,c,d,e=np.split(abc,[3,5,8,10])
print(a,b,c,d,e)

[1 2 3] [4 5] [6 7 8] [ 9 10] [11 12]


In [57]:
newgrid=np.arange(12).reshape((3,4))
newgrid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
#horizontal split
n1,n2=np.hsplit(newgrid,[2])
print("n1=",n1)
print("n2=",n2)

n1= [[0 1]
 [4 5]
 [8 9]]
n2= [[ 2  3]
 [ 6  7]
 [10 11]]


In [59]:
#vertical split
n3,n4=np.vsplit(newgrid,[1])
print(n3)
print(n4)

[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]


In [65]:
#aggregates
p=np.arange(1,10)
print(p)
print("Sum of array elements: ",np.add.reduce(p))
print("Product of array elements: ",np.multiply.reduce(p))

[1 2 3 4 5 6 7 8 9]
Sum of array elements:  45
Product of array elements:  362880


In [67]:
np.add.accumulate(p)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [68]:
np.multiply.accumulate(p)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)